### ISSUE TITLE
Oauth 1 and Oauth 2

### ISSUE THREAD

**Issue by marabesi** [consolibyte/quickbooks-php#184] opened 2017-09-26 20:51 UTC
As Intuit has updated its authentication method to be Oauth 2 is there a way to still using Oauth 1 in apps created as Oauth2?

If not is there a way to create new apps using Oauth 1?

**Comment by consolibyte** [comment] 2019-05-16 22:42
This is a duplicate of #181 - OAuth v2.0 support.

**Closed by consolibyte** 2019-05-16 22:42 UTC

**Comment by consolibyte** [comment] 2019-05-16 23:46
The 3.6 release has working OAuth v2.0 support now. OpenID Connect and an automated OAuth v1 to v2 migration process are coming soon.

https://github.com/consolibyte/quickbooks-php/releases/tag/v3.6

Manual migration (e.g. you have to reconnect via the OAuth flow) instructions are here:
https://github.com/consolibyte/quickbooks-php/blob/master/README_OAUTHV1_TO_OAUTHV2.md

ALSO -- Migrate your app to OAuth 2.0 before May 31 and you could win a limited edition Intuit hoodie, PLUS if you tell Intuit about your migration plans, you’ll gain entry to win the entertainment system of your dreams. Find out more here: https://intuit.me/OAuth2
